# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
%define utempter_compat_ver 0.5.2
# << macros

Name:       libutempter
Summary:    A privileged helper for utmp/wtmp updates
Version:    1.1.5
Release:    2
Group:      System/Libraries
License:    LGPLv2
URL:        ftp://ftp.altlinux.org/pub/people/ldv/utempter
Source0:    ftp://ftp.altlinux.org/pub/people/ldv/utempter/%{name}-%{version}.tar.bz2
Source100:  libutempter.yaml
Requires(pre): shadow-utils
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   utempter = %{utempter_compat_ver}
Obsoletes:   utempter


%description
This library provides interface for terminal emulators such as
screen and xterm to record user sessions to utmp and wtmp files.



%package devel
Summary:    Development environment for utempter
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains development files required to build
utempter-based software.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
make CFLAGS="$RPM_OPT_FLAGS" libdir="%{_libdir}" libexecdir="%{_libexecdir}"
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make install DESTDIR="$RPM_BUILD_ROOT" libdir="%{_libdir}" libexecdir="%{_libexecdir}"
# NOTE: Static lib intentionally disabled.
rm -f $RPM_BUILD_ROOT%{_libdir}/*.a
# << install post

%pre
# >> pre
{
%{_sbindir}/groupadd -g 22 -r -f utmp || :
%{_sbindir}/groupadd -g 35 -r -f utempter || :
}
# << pre


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc COPYING README
%{_libdir}/libutempter.so.0
%{_libdir}/libutempter.so.1.1.5
%dir %attr(755,root,utempter) %{_libexecdir}/utempter
%attr(2711,root,utmp) %{_libexecdir}/utempter/utempter
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/utempter.h
%{_libdir}/libutempter.so
# << files devel

